---
title: "Sankey Code"
author: "Foster Thorburn"
date: "2023-09-07"
output: html_document
---

```{r, warning=FALSE}
library(plotly)
```

```{r}


fig <- plot_ly(
    type = "sankey",
    orientation = "h",

    node = list(
      label = c("All UC Events", 
                "Long Term", 
                "Short Term", 
                "Case Filings", 
                "Cases Closed", 
                "MCH", 
                "State Court Hearings", 
                "LT Rep Initiated", 
                "KYRs", 
                "Initial Legal Screenings", 
                "ST Rep Initiated", 
                "VD Cases", 
                "I-360s", 
                "I-485s", 
                "I-589s", 
                "I-765s",
                "I-131s",
                "N-600s"),
      color = c("grey", 
                "grey", 
                "grey", 
                "rgba(255, 0, 0, 0.6)"),
      pad = 15,
      thickness = 20,
      line = list(
        color = "black",
        width = 0.5
      )
    ),

    link = list(
      source = c(0,0,1,3,3,3,3,1,1,1,1,2,2,2,2,3,3),
      target = c(1,2,3,12,13,14,15,4,5,6,7,8,9,10,11,16,17),
      value =  c(518,717,226,52,4,63,104,40,94,23,135,331,350,33,3,2,1),
      color = c( "rgba(0, 113, 188, 0.6",    
                 "rgba(0, 113, 188, 0.6)",     
                 "rgba(255, 0, 0, 0.6)",  
                 "rgba(204, 0, 0, 0.6)",       
                 "rgba(255, 128, 0, 0.6)",    
                 "rgba(255, 51, 153, 0.6)",  
                 "rgba(255, 68, 68, 0.6)",    
                 "rgba(139, 0, 0, 0.6)",  
                 "rgba(255, 215, 0, 0.6)",     
                 "rgba(255, 187, 51, 0.6)",   
                 "rgba(255, 128, 0, 0.6)",    
                 "rgba(102, 204, 0, 0.6)",    
                 "rgba(0, 128, 128, 0.6)",    
                 "rgba(34, 139, 34, 0.6)",  
                 "rgba(102, 153, 255, 0.6)",
                 "rgba(255, 165, 0, 0.6)",  
                 "rgba(255, 204, 153, 0.6)" )  
  
    )
  )

#think of each column as a single stream, 1st value in the column is where it starts, second is where it goes, and 3rd value is how big it is 
# X
# Y
# Z


fig <- fig %>% layout(
    title = "Sankey Diagram of UC MIRC Events and Filings 01/01/23 - 06/30/23",
    font = list(
      size = 11
    )
)

fig
```

